# -*- coding: utf-8 -*-
"""Image_Feature_Extraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nXIQ5NfEGu6dDdKitd2pROO3kPhdi_8G
"""

!unzip "/content/drive/My Drive/122238_294885_bundle_archive.zip"

from os import listdir
from os import path
from pickle import dump
from keras.applications.vgg16 import VGG16
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.applications.vgg16 import preprocess_input
from keras.models import Model

len(listdir("/content/Flickr_Data/Images"))

"""## FEATURE EXTRACTION FROM IMAGES

### LOAD MODEL (VGG16)
"""

def load_model():
  model = VGG16()
  #removing the last layer from the loaded model
  model.layers.pop()
  return Model(inputs=model.inputs, outputs=model.layers[-1].output)

def summary(model):
  model.summary()

"""### EXTRACTING FEATUES"""

def extract_features(directory,model):
  features = dict()
  for name in listdir(directory):
    filename = path.join(directory, name)
    image = load_img(filename, target_size=(224, 224))
    image = img_to_array(image)

    image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
    image = preprocess_input(image)

    feature = model.predict(image, verbose=0)

    image_id = name.split('.')[0]
    features[image_id] = feature

    print('>%s' % name)
  return features

directory ="/content/Flickr_Data/Images"
model=load_model()
summary(model)

features = extract_features(directory,model)

"""### SAVE THE DICT"""

dump(features, open('features.pkl', 'wb'))